# Generated by Django 5.1.3 on 2025-11-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('poster', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('original_name', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=500, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('keyword_1', models.CharField(blank=True, choices=[('acao', 'Ação'), ('animacao', 'Animação'), ('aventura', 'Aventura'), ('biografia', 'Biografia'), ('comedia', 'Comédia'), ('crime', 'Crime'), ('documentario', 'Documentário'), ('drama', 'Drama'), ('fantasia', 'Fantasia'), ('ficcao', 'Ficção'), ('familia', 'Família'), ('guerra', 'Guerra'), ('historia', 'História'), ('misterio', 'Mistério'), ('musical', 'Musical'), ('policial', 'Policial'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('esporte', 'Esporte')], max_length=50, null=True)),
                ('keyword_2', models.CharField(blank=True, choices=[('acao', 'Ação'), ('animacao', 'Animação'), ('aventura', 'Aventura'), ('biografia', 'Biografia'), ('comedia', 'Comédia'), ('crime', 'Crime'), ('documentario', 'Documentário'), ('drama', 'Drama'), ('fantasia', 'Fantasia'), ('ficcao', 'Ficção'), ('familia', 'Família'), ('guerra', 'Guerra'), ('historia', 'História'), ('misterio', 'Mistério'), ('musical', 'Musical'), ('policial', 'Policial'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('esporte', 'Esporte')], max_length=50, null=True)),
                ('keyword_3', models.CharField(blank=True, choices=[('acao', 'Ação'), ('animacao', 'Animação'), ('aventura', 'Aventura'), ('biografia', 'Biografia'), ('comedia', 'Comédia'), ('crime', 'Crime'), ('documentario', 'Documentário'), ('drama', 'Drama'), ('fantasia', 'Fantasia'), ('ficcao', 'Ficção'), ('familia', 'Família'), ('guerra', 'Guerra'), ('historia', 'História'), ('misterio', 'Mistério'), ('musical', 'Musical'), ('policial', 'Policial'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('esporte', 'Esporte')], max_length=50, null=True)),
                ('keyword_4', models.CharField(blank=True, choices=[('series', 'Séries'), ('filmes', 'Filmes')], max_length=50, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('movie', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
